-- MySQL Script generated by MySQL Workbench
-- Wed Jan 10 00:51:51 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema flutter_160420002
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flutter_160420002
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flutter_160420002` DEFAULT CHARACTER SET utf8 ;
USE `flutter_160420002` ;

-- -----------------------------------------------------
-- Table `flutter_160420002`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_160420002`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `photo` LONGTEXT NULL,
  `password` LONGTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_160420002`.`dolans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_160420002`.`dolans` (
  `id` INT NOT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `jumlah_minimal` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_160420002`.`jadwals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_160420002`.`jadwals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(45) NOT NULL,
  `tanggal` TIMESTAMP NOT NULL,
  `lokasi` VARCHAR(45) NOT NULL,
  `alamat` LONGTEXT NOT NULL,
  `jadwalscol` VARCHAR(45) NOT NULL,
  `users_id` INT NOT NULL,
  `dolans_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_jadwals_users1_idx` (`users_id` ASC),
  INDEX `fk_jadwals_dolans1_idx` (`dolans_id` ASC),
  CONSTRAINT `fk_jadwals_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `flutter_160420002`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jadwals_dolans1`
    FOREIGN KEY (`dolans_id`)
    REFERENCES `flutter_160420002`.`dolans` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_160420002`.`ngobrols`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_160420002`.`ngobrols` (
  `id` INT NOT NULL,
  `tanggal` TIMESTAMP NOT NULL,
  `chat` LONGTEXT NOT NULL,
  `users_id` INT NOT NULL,
  `jadwals_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ngobrols_users1_idx` (`users_id` ASC),
  INDEX `fk_ngobrols_jadwals1_idx` (`jadwals_id` ASC),
  CONSTRAINT `fk_ngobrols_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `flutter_160420002`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ngobrols_jadwals1`
    FOREIGN KEY (`jadwals_id`)
    REFERENCES `flutter_160420002`.`jadwals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flutter_160420002`.`users_has_jadwals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flutter_160420002`.`users_has_jadwals` (
  `users_id` INT NOT NULL,
  `jadwals_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `jadwals_id`),
  INDEX `fk_users_has_jadwals_jadwals1_idx` (`jadwals_id` ASC),
  INDEX `fk_users_has_jadwals_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_jadwals_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `flutter_160420002`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_jadwals_jadwals1`
    FOREIGN KEY (`jadwals_id`)
    REFERENCES `flutter_160420002`.`jadwals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
